// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// // import "../lib/i18n"; // Import i18next config
// import "./globals.css";
// import { useLocale } from 'next-intl';
// import enMessages from '@/public/locales/en/common.json';
// import faMessages from '@/public/locales/fa/common.json';
// import { NextIntlClientProvider } from 'next-intl';

// const messages = { en: enMessages, fa: faMessages };


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// function RootLayout({
//   children, params
// }: Readonly<{
//   children: React.ReactNode;
//   params?: any
// }>) {
//   const { locale } = params;
//   return (
//     <html lang={locale}>
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         <NextIntlClientProvider locale={locale} messages={messages[locale]}>
//           {children}
//         </NextIntlClientProvider>
//       </body>
//     </html>
//   );
// }
// export default RootLayout;


// // //===========

// // // import type { Metadata } from "next";
// // // import { Geist, Geist_Mono } from "next/font/google";
// // // import "./globals.css";
// // // import i18nextConfig from "../next-i18next.config";

// // // const geistSans = Geist({
// // //   variable: "--font-geist-sans",
// // //   subsets: ["latin"],
// // // });

// // // const geistMono = Geist_Mono({
// // //   variable: "--font-geist-mono",
// // //   subsets: ["latin"],
// // // });

// // // export const metadata: Metadata = {
// // //   title: "Create Next App",
// // //   description: "Generated by create next app",
// // // };

// // // export default function RootLayout({
// // //   children,
// // //   params,
// // // }: {
// // //   children: React.ReactNode;
// // //   params: { locale: string };
// // // }) {
// // //   const locale =
// // //     i18nextConfig.i18n.locales.includes(params.locale) && params.locale
// // //       ? params.locale
// // //       : i18nextConfig.i18n.defaultLocale;

// // //   return (
// // //     <html lang={locale}>
// // //       <body className={`${geistSans.variable} ${geistMono.variable}`}>
// // //         {children}
// // //       </body>
// // //     </html>
// // //   );
// // // }

// ==========

import { NextIntlClientProvider } from 'next-intl';

type Props = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: Props) {
  return (
    <html>
      <body>
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}